#!/usr/bin/env bash
set -euo pipefail

mkdir -p reports

TIMESTAMP=$(date +%F_%H-%M-%S)
REPORT="reports/system_audit_${TIMESTAMP}.txt"

section() {
  echo
  echo "============================================================"
  echo "$1"
  echo "============================================================"
}

{
  section "SYSTEM AUDIT REPORT"
  echo "Generated at : $(date)"
  echo "Generated by : $(whoami)"
  echo "Working dir  : $(pwd)"

  section "1. HOST AND OS"
  hostnamectl || true
  echo
  cat /etc/os-release || true
  echo
  uname -a || true

  section "2. UPTIME AND RESOURCE SUMMARY"
  uptime || true
  echo
  lscpu | head -n 25 || true
  echo
  free -h || true
  echo
  df -hT || true

  section "3. NETWORK INTERFACES AND LISTENING PORTS"
  ip -brief addr || true
  echo
  ss -tulpen || true

  section "4. USERS WITH LOGIN SHELL"
  awk -F: '$7 !~ /(nologin|false)$/ {print $1 ":" $3 ":" $6 ":" $7}' /etc/passwd || true

  section "5. SUDO GROUP MEMBERS"
  getent group sudo || true

  section "6. RUNNING SERVICES"
  systemctl --type=service --state=running --no-pager || true

  section "7. ENABLED SERVICES"
  systemctl list-unit-files --type=service --state=enabled --no-pager || true

  section "8. FIREWALL STATUS"
  sudo ufw status verbose || true

  section "9. PACKAGE UPDATES AVAILABLE"
  apt list --upgradable 2>/dev/null || true

  section "10. RECENT AUTH LOG ENTRIES"
  if [ -f /var/log/auth.log ]; then
    sudo tail -n 80 /var/log/auth.log || true
  else
    echo "/var/log/auth.log not found. On some systems, auth logs may be in journalctl."
  fi

  section "11. RECENT SYSTEM ERRORS"
  journalctl -p 3 -xb --no-pager -n 80 || true

  section "12. WORLD-WRITABLE FILES IN HOME"
  find /home -xdev -type f -perm -0002 -print 2>/dev/null | head -n 50 || true
} | tee "$REPORT"

echo
echo "Report saved to: $REPORT"
